### ISSUE TITLE
broken natives functions

### ISSUE THREAD

**Issue by zottce** [ZOTTCE/samp-sdk#18]
SDK breaks native functions from other modules (like SAMP and plugins) when plugin uses `#[native(..., raw)]` or `samp_sdk::amx::Allocator` and its methods (I'm not sure which one).

@bmisiak

**Comment by zottce** [comment]
relative issue is https://github.com/bmisiak/samp-precise-timers/issues/7

**Comment by bmisiak** [comment]
Hey @ZOTTCE, thanks for filing the issue!

Interesting. From a brief look at 

https://github.com/Zeex/sampgdk/blob/599a1227f845fc8931059c6c9ee82c0776483a7e/lib/sampgdk/internal/native.c#L67-L68 

I thought perhaps it had something to do with native ordering.

**Comment by zottce** [comment]
@bmisiak 
I don't think that this error has any relationships with `sampgdk`, because I couldn't successfully call `UpdatePlayer3DTextLabelText` without GDK plugin.

**Comment by Southclaws** [comment]
I've heard similar reports from users of my Rust plugins: https://github.com/Southclaws/pawn-json/issues/2#issuecomment-645951131

**Comment by Southclaws** [comment]
I removed all `native(raw, ...` from my code and the issue still occurred.

**Comment by zottce** [comment]
@Southclaws could you help me to test bugfix?
I guess this commit (zottce/samp-rs@2e9192713bf9a77ee04e0ebbcda37d078c9c47dd) in `potential-fix` branch should fix this annoying bug.

**Comment by zottce** [comment]
That branch should be a fix, I've tested it on Windows and didn't get warnings. On ubuntu 20.04 I couldn't reproduce this bug maybe because of different memory management (Windows could reuse this regions while Ubuntu isn't). sampgdk saves pointers to natives names in the `amx_Register` hook (but samp implementation of AMX doesn't do that). Currently in the master branch I free memory containing strings with names that decision is based on original AMX.

@bmisiak @Southclaws @Sreyas-Sreelal
