### ISSUE TITLE
Solved

### ISSUE THREAD

**Issue by LDarki** [ZOTTCE/samp-sdk#19]
The question is already in the title :P

**Comment by zottce** [comment]
Nope. AMX doesn't allow you to preform this action.
You should pass an allocated array from gamemode / filterscript.

There is an example for that: https://github.com/ZOTTCE/samp-rs/blob/master/plugin-example/src/lib.rs#L65

`native Memcached_GetString(connection, const key[], retval[], size_of_retval);`
