### ISSUE TITLE
Is there a way to listen to callbacks?

### ISSUE THREAD

**Issue by Kaperstone** [ZOTTCE/samp-sdk#4]
A way to fire an event in Rust when, for example, `OnPlayerConnect` is called?

**Comment by zottce** [comment]
Yes, you can do it, look [here](http://forum.sa-mp.com/showthread.php?t=574534) and [there](http://forum.sa-mp.com/showthread.php?t=295798) at `Hooking callbacks`

**Comment by Kaperstone** [comment]
Well, I actually thought if there is a way to hook to callbacks from within Rust and SAMP-SDK only without interacting with Pawn.
